deepseek:
  api_key: ${DEEPSEEK_API_KEY}
  base_url: https://api.deepseek.com
  model: deepseek-chat
  temperature: 
    excel: "1.0"
    mind_summarize: "1.5"
    chat: "1.3"
    word: "1.5"
  stream:
    excel: "false"
    mind_summarize: "true"
    word: "true"
    chat: "true"
  response_format:
    excel: text
    mind_summarize: text
    word: text
    chat: text
mongo:
  mongo_uri: ${MONGO_URI}

file_path:
#local路径
  base_file_path: "./user_file/" 
# 线上路径
  # base_file_path: "/user_file/"

base_url:
  # local
  base_url: "http://localhost:8000/api/v1/" 
  # 线上
