deepseek:
  api_key: ${DEEPSEEK_API_KEY}
  base_url: https://api.deepseek.com
  model: deepseek-chat

mongo:
  mongo_uri: ${MONGO_URI}

file_path:
#local路径
  base_file_path: "./user_file/" 
# 线上路径
  # base_file_path: "/user_file/"

base_url:
  # local
  base_url: "http://0.0.0.0:8000/api/v1/" 
  # 线上
